[package]
name = "battleship"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ff = "0.4.0"
ark-groth16 = "0.4.0"
ark-relations = "0.4.0"

[dev-dependencies]
ark-bls12-381 = "0.4.0"
ark-std = "0.4.0"
